"""Build the 3-task cross-task comparison table (cross-task.tex) from the
ZERO-SHOT data, preserving the user's polished colored-cell format.

All three columns are now matched 0-shot CoT, Qwen3-8B, single L40S,
max_num_seqs=256, same 8-language subset:
  - Belebele : 0-shot canonical CSV (belebele_canonical_Qwen3-8B_0shot.csv,
               field steady_energy_per_token_J; the 8-lang slice of the
               122-lang reference run, 900 req).
  - GSM8K    : 0-shot, 272x3=816 effective req
               (belebele_0shot_seqs256_Qwen__Qwen3-8B_gsm8k_8lang).
  - LM-Arena : 0-shot, 266x3=798 effective req
               (..._lmarena_8lang).

Writes the colored LaTeX table to the paper-update-1 tree and prints the
disparities. Color is a continuous white->red gradient matching the cells in
the user's existing table (reverse-engineered linear fit, anchored so 0.087
J/tok ~ near-white and ~1.35 J/tok ~ EDA19A); this keeps energy magnitude
visually comparable to the rest of the paper.
"""
from __future__ import annotations

import csv
import glob
import json
import os
from pathlib import Path

REPO = Path(".")
RUN = REPO / "benchmark" / "run" / "llm" / "lmarena_qwen8b_L40S_12langs"
BEL_CSV = (REPO.parent / "shared_data" / "MLEnergy" / "research"
           / "lmarena_translate" / "belebele_canonical_Qwen3-8B_0shot.csv")
BEL_CSV = (Path(".")
           / "research" / "lmarena_translate"
           / "belebele_canonical_Qwen3-8B_0shot.csv")
OUT_TEX = (Path(".")
           / "paper" / "paper-update-1" / "extracted" / "tables"
           / "cross-task.tex")

TIERS = [
    ("High", ["eng_Latn", "zho_Hans", "rus_Cyrl", "fra_Latn"]),
    ("Low",  ["pbt_Arab", "tir_Ethi", "shn_Mymr", "bod_Tibt"]),
]
LANGS = [l for _, ls in TIERS for l in ls]


def clamp(x: float) -> int:
    return max(0, min(255, round(x)))


def cell_color(v: float) -> str:
    """White->red gradient matching the user's existing table cells."""
    d = max(0.0, v - 0.087)
    r = clamp(255 - 14.25 * d)
    g = clamp(252 - 72.05 * d)
    b = clamp(252 - 77.60 * d)
    return f"{r:02X}{g:02X}{b:02X}"


def read_task(task: str, lang: str) -> dict | None:
    fs = [f for f in glob.glob(
        f"{RUN}/belebele_0shot_seqs256_Qwen__Qwen3-8B_{task}_8lang/{lang}/"
        f"local-jsonl-bench/results/Qwen/Qwen3-8B/*/*/results.json")
        if os.path.getsize(f) > 0]
    if not fs:
        return None
    d = json.load(open(fs[0]))
    return {"jpt": d["steady_state_energy_per_token"],
            "completed": d["completed"], "num_prompts": d["num_prompts"]}


def main() -> None:
    bel = {}
    with open(BEL_CSV) as f:
        for row in csv.DictReader(f):
            bel[row["language"]] = float(row["steady_energy_per_token_J"])

    data = {}
    cens = []  # (lang, task, completed, num_prompts)
    for L in LANGS:
        g, a = read_task("gsm8k", L), read_task("lmarena", L)
        assert g and a, f"missing 0-shot cross-task result for {L}"
        data[L] = {"Belebele": bel[L], "GSM8K": g["jpt"], "LM-A": a["jpt"]}
        if g["completed"] < g["num_prompts"]:
            cens.append((L, "GSM8K", g["completed"], g["num_prompts"]))
        if a["completed"] < a["num_prompts"]:
            cens.append((L, "LM-Arena", a["completed"], a["num_prompts"]))

    disp = {}
    for col in ("Belebele", "GSM8K", "LM-A"):
        vals = {L: data[L][col] for L in LANGS}
        lo_l = min(vals, key=vals.get)
        hi_l = max(vals, key=vals.get)
        disp[col] = (vals[lo_l], vals[hi_l], vals[hi_l] / vals[lo_l], lo_l, hi_l)

    def daggers(L, col):
        for (cl, ct, _, _) in cens:
            if cl == L and ((col == "GSM8K" and ct == "GSM8K")
                            or (col == "LM-A" and ct == "LM-Arena")):
                return r"$^\dagger$"
        return ""

    out = []
    p = out.append
    p("% Auto-generated by research/lmarena_translate/build_crosstask_table_0shot.py")
    p("% All three columns are matched 0-shot CoT: Qwen3-8B, single L40S,")
    p("% max_num_seqs=256, same 8-language subset. Steady-state J / output")
    p("% token. Belebele = 0-shot 122-lang reference (900 req); translated")
    p("% GSM8K = 272x3=816 req; LM-Arena = 266x3=798 req. Steady-state")
    p("% per-token energy is request-count-invariant by construction.")
    p(r"\begin{table}[t]")
    p(r"  \centering")
    p(r"  \small")
    p(r"  \renewcommand{\arraystretch}{1.4}")
    p(r"  \resizebox{\linewidth}{!}{")
    p(r"  \begin{tabular}{clrrr}")
    p(r"    \toprule")
    p(r"    & & \multicolumn{3}{c}{\textbf{J\,/\,output token}} \\")
    p(r"    \cmidrule(lr){3-5}")
    p(r"    \textbf{Resource} & \textbf{Language} & \textbf{Belebele} & "
      r"\textbf{GSM8K} & \textbf{LM-A} \\")
    p(r"    & & {(reading)} & {\footnotesize(math)} & {\footnotesize(chat)} \\")
    p(r"    \midrule")
    for ti, (tier, langs) in enumerate(TIERS):
        for j, L in enumerate(langs):
            tcell = (f"\\multirow{{4}}{{*}}{{{tier}}}" if j == 0 else "")
            code = L.replace("_", r"\_")
            cells = []
            for col in ("Belebele", "GSM8K", "LM-A"):
                v = data[L][col]
                cells.append(f"\\cellcolor[HTML]{{{cell_color(v)}}}"
                             f"{v:.3f}{daggers(L, col)}")
            lead = f"{tcell} & " if j == 0 else " & "
            p(f"    {lead}\\texttt{{{code}}} & " + " & ".join(cells) + r" \\")
        if ti < len(TIERS) - 1:
            p(r"    \midrule")
    p(r"    \bottomrule")
    p(r"  \end{tabular}}")
    cen_txt = "; ".join(f"\\texttt{{{cl.replace('_', chr(92)+'_')}}} "
                        f"{c}/{n} ({ct})" for (cl, ct, c, n) in cens)
    p(r"  \caption{Energy per output token for Qwen3-8B on the same "
      r"8-language subset across three datasets, all under matched "
      r"zero-shot CoT prompting and an identical serving configuration "
      r"(single L40S, \texttt{max\_num\_seqs}=256). "
      r"The cross-language disparity persists under every task: max/min "
      r"over the 8 languages is "
      f"${disp['Belebele'][2]:.1f}\\times$ (Belebele), "
      f"${disp['GSM8K'][2]:.1f}\\times$ (GSM8K), and "
      f"${disp['LM-A'][2]:.1f}\\times$ (LM-Arena), with English or Chinese "
      r"cheapest and Tibetan most expensive in all three. "
      f"$^\\dagger$Right-censored (hit the 6-hour cap: {cen_txt}); the "
      r"steady-state window still formed, so per-token energy is valid "
      r"(cf.\ Limitations).}")
    p(r"  \label{tab:cross_task}")
    p(r"\end{table}")
    OUT_TEX.write_text("\n".join(out) + "\n")

    print(f"Wrote {OUT_TEX}")
    for col, (lo, hi, ratio, ll, lh) in disp.items():
        print(f"  {col:9s}: {lo:.3f} ({ll}) -> {hi:.3f} ({lh}) = {ratio:.1f}x")
    print("  censored:", cens)


if __name__ == "__main__":
    main()
