"""Build the cross-GPU table (table_cross_gpu.tex): Qwen3-8B 0-shot Belebele,
8-lang subset, steady-state J/output token, L40S vs RTX 6000 Pro Blackwell, at
the paper's fixed serving config max_num_seqs=256.

Both columns come from the batch-size sweeps at bs=256:
  L40S : research/lmarena_translate/belebele_seqsweep_l40s_0shot.csv
  RTX  : research/cross_gpu/seqsweep_belebele_v1_qwen8b_RTX6000_all8.csv
(per-token energy is request-count invariant, so the differing repeat counts
are comparable). Colored cells use the same white->red gradient as the
cross-task table.
"""
from __future__ import annotations

import csv
from pathlib import Path

REPO = Path(".")
OUT = REPO / "paper" / "paper-update-1" / "extracted" / "tables" / "table_cross_gpu.tex"
L40S_CSV = REPO / "research" / "lmarena_translate" / "belebele_seqsweep_l40s_0shot.csv"
RTX_CSV = REPO / "research" / "cross_gpu" / "seqsweep_belebele_v1_qwen8b_RTX6000_all8.csv"
BS = 256

TIERS = [("High", ["eng_Latn", "zho_Hans", "rus_Cyrl", "fra_Latn"]),
         ("Low",  ["pbt_Arab", "tir_Ethi", "shn_Mymr", "bod_Tibt"])]
LANGS = [l for _, ls in TIERS for l in ls]


def clamp(x): return max(0, min(255, round(x)))


def cell_color(v):
    d = max(0.0, v - 0.087)
    return f"{clamp(255-14.25*d):02X}{clamp(252-72.05*d):02X}{clamp(252-77.6*d):02X}"


def main():
    l40s = {}
    with open(L40S_CSV) as f:
        for r in csv.DictReader(f):
            if int(r["max_num_seqs"]) == BS:
                l40s[r["language"]] = float(r["jpt"])
    rtx = {}
    with open(RTX_CSV) as f:
        for r in csv.DictReader(f):
            if int(r["bsz"]) == BS:
                rtx[r["lang"]] = float(r["jpt"])

    dL = max(l40s[l] for l in LANGS) / min(l40s[l] for l in LANGS)
    dR = max(rtx[l] for l in LANGS) / min(rtx[l] for l in LANGS)

    out = []
    p = out.append
    p("% Auto-generated by research/lmarena_translate/build_cross_gpu_table.py")
    p("% Qwen3-8B 0-shot Belebele, 8-lang subset, steady-state J/output token,")
    p(f"% max_num_seqs={BS}. L40S + RTX 6000 Pro Blackwell from the bs={BS} sweep.")
    p(r"\begin{table}[t]")
    p(r"  \centering")
    p(r"  \small")
    p(r"  \renewcommand{\arraystretch}{1.4}")
    p(r"  \begin{tabular}{clrr}")
    p(r"    \toprule")
    p(r"    & & \multicolumn{2}{c}{\textbf{J\,/\,output token}} \\")
    p(r"    \cmidrule(lr){3-4}")
    p(r"    \textbf{Resource} & \textbf{Language} & \textbf{L40S} & \textbf{RTX~6000} \\")
    p(r"    \midrule")
    for ti, (tier, langs) in enumerate(TIERS):
        for j, L in enumerate(langs):
            lead = f"\\multirow{{4}}{{*}}{{{tier}}} & " if j == 0 else " & "
            code = L.replace("_", r"\_")
            p(f"    {lead}\\texttt{{{code}}} & "
              f"\\cellcolor[HTML]{{{cell_color(l40s[L])}}}{l40s[L]:.2f} & "
              f"\\cellcolor[HTML]{{{cell_color(rtx[L])}}}{rtx[L]:.2f} \\\\")
        if ti < len(TIERS) - 1:
            p(r"    \midrule")
    p(r"    \bottomrule")
    p(r"  \end{tabular}")
    p(r"  \caption{Energy per output token for Qwen3-8B on the 8-language "
      r"Belebele subset (0-shot CoT, \texttt{max\_num\_seqs}=256), L40S vs.\ "
      r"RTX~6000 Pro Blackwell. The cross-language disparity is present on both "
      r"GPUs but its magnitude is strongly hardware-dependent: max/min is "
      f"${dL:.1f}\\times$ on the L40S versus only ${dR:.1f}\\times$ on the "
      r"RTX. High-resource per-token energy is similar across GPUs; the gap "
      r"comes almost entirely from the low-resource languages, whose long "
      r"generations are far cheaper per token on the higher-bandwidth RTX.}")
    p(r"  \label{tab:cross_gpu}")
    p(r"\end{table}")
    OUT.write_text("\n".join(out) + "\n")
    print(f"Wrote {OUT}")
    print(f"  L40S disparity @bs{BS}: {dL:.1f}x | RTX disparity @bs{BS}: {dR:.1f}x")


if __name__ == "__main__":
    main()
