"""Build the cross-model table (cross-model-heatmap.tex): Qwen3-8B 0-shot
Belebele 8-lang subset, steady-state J/output token, across four models
served on a single L40S at max_num_seqs=256:
  Qwen3-8B, Qwen3-14B, Qwen3-32B, Llama-3.1-8B.

Sources: Qwen3-8B from the 0-shot canonical CSV; the other three from their
belebele_0shot_seqs256_<model>_8lang run dirs. Colored cells use the same
white->red gradient as the cross-task / cross-GPU tables. Right-censored cells
(hit the 6h cap) are marked with a dagger.
"""
from __future__ import annotations

import csv
import glob
import json
import os
from pathlib import Path

REPO = Path(".")
RUN = Path("./benchmark/run/llm/lmarena_qwen8b_L40S_12langs")
BEL_CSV = REPO / "research" / "lmarena_translate" / "belebele_canonical_Qwen3-8B_0shot.csv"
OUT = REPO / "paper" / "paper-update-1" / "extracted" / "tables" / "cross-model-heatmap.tex"

TIERS = [("High", ["eng_Latn", "zho_Hans", "rus_Cyrl", "fra_Latn"]),
         ("Low",  ["pbt_Arab", "tir_Ethi", "shn_Mymr", "bod_Tibt"])]
LANGS = [l for _, ls in TIERS for l in ls]
# (display header, run-dir tag or None for the canonical-CSV base model)
MODELS = [
    ("Qwen3-8B", None),
    ("Qwen3-14B", "Qwen__Qwen3-14B"),
    ("Qwen3-32B", "Qwen__Qwen3-32B"),
    ("gemma-3-27B", "google__gemma-3-27b-it"),
    ("Llama-3.1-8B", "meta-llama__Llama-3.1-8B-Instruct"),
]


def clamp(x): return max(0, min(255, round(x)))


def cell_color(v):
    d = max(0.0, v - 0.087)
    return f"{clamp(255-14.25*d):02X}{clamp(252-72.05*d):02X}{clamp(252-77.6*d):02X}"


def read_model(tag):
    """Return {lang: (jpt, completed, num_prompts)} for a run-dir model."""
    out = {}
    for L in LANGS:
        g = [x for x in glob.glob(
            f"{RUN}/belebele_0shot_seqs256_{tag}_8lang/{L}/**/results.json",
            recursive=True) if os.path.getsize(x) > 0]
        d = json.load(open(g[0]))
        out[L] = (d["steady_state_energy_per_token"], d["completed"], d["num_prompts"])
    return out


def main():
    base = {}
    with open(BEL_CSV) as f:
        for r in csv.DictReader(f):
            if r["language"] in LANGS:
                base[r["language"]] = (float(r["steady_energy_per_token_J"]), 900, 900)
    data = {}
    for disp, tag in MODELS:
        data[disp] = base if tag is None else read_model(tag)

    disp_ratio = {}
    for disp, _ in MODELS:
        v = {L: data[disp][L][0] for L in LANGS}
        disp_ratio[disp] = max(v.values()) / min(v.values())
    cens = [(disp, L) for disp, _ in MODELS for L in LANGS
            if data[disp][L][1] < data[disp][L][2]]

    # CSV sidecar (full-precision J/tok + completed counts so censoring is explicit)
    tier_of = {L: t for t, ls in TIERS for L in ls}
    csv_path = OUT.with_suffix(".csv")
    with open(csv_path, "w", newline="") as f:
        w = csv.writer(f)
        cols = ["resource", "language"]
        for disp, _ in MODELS:
            cols += [f"{disp}_jpt", f"{disp}_completed"]
        w.writerow(cols)
        for L in LANGS:
            row = [tier_of[L], L]
            for disp, _ in MODELS:
                jpt, c, n = data[disp][L]
                row += [f"{jpt:.4f}", f"{c}/{n}"]
            w.writerow(row)
        w.writerow([])
        w.writerow(["disparity (max/min)", ""] +
                   [x for disp, _ in MODELS for x in (f"{disp_ratio[disp]:.2f}", "")])
    print(f"Wrote {csv_path}")

    out = []
    p = out.append
    p("% Auto-generated by research/lmarena_translate/build_cross_model_table.py")
    p("% Qwen3-8B 0-shot Belebele, 8-lang subset, steady-state J/output token,")
    p("% single L40S, max_num_seqs=256. 5 models: Qwen3-8B/14B/32B + gemma-3-27B + Llama-3.1-8B.")
    p(r"\begin{table}[t]")
    p(r"\centering")
    p(r"\small")
    p(r"\renewcommand{\arraystretch}{1.4}")
    p(r"\resizebox{\linewidth}{!}{")
    p(r"\begin{tabular}{cl" + "c" * len(MODELS) + "}")
    p(r"\toprule")
    hdr = " & ".join(f"\\multicolumn{{1}}{{l}}{{{m}}}" for m, _ in MODELS)
    p(f"Resource & Language & {hdr} \\\\")
    p(r"\midrule")
    for ti, (tier, langs) in enumerate(TIERS):
        for j, L in enumerate(langs):
            lead = f"\\multirow{{4}}{{*}}{{{tier}}} & " if j == 0 else "& "
            cells = []
            for disp, _ in MODELS:
                v, c, n = data[disp][L]
                dag = r"$^\dagger$" if c < n else ""
                cells.append(f"\\cellcolor[HTML]{{{cell_color(v)}}}{v:.2f}{dag}")
            p(f"{lead}{L.replace('_', chr(92)+'_')} & " + " & ".join(cells) + r" \\")
        p(r"\midrule" if ti < len(TIERS) - 1 else "")
    p(r"\bottomrule")
    p(r"\end{tabular}}")
    lo = min(disp_ratio.values()); hi = max(disp_ratio.values())
    cen_txt = ", ".join(f"\\texttt{{{L.replace('_', chr(92)+'_')}}} on {m}"
                        for m, L in cens)
    per_model = ", ".join(f"${disp_ratio[m]:.1f}\\times$ {m}" for m, _ in MODELS)
    nwords = {4: "four", 5: "five", 6: "six"}.get(len(MODELS), str(len(MODELS)))
    p(r"\caption{Per-language energy per output token (steady-state J / output "
      r"token) on the 8-language Belebele subset (four high- and four "
      f"low-resource languages under the NLLB taxonomy), for {nwords} models "
      r"served on a single L40S at \texttt{max\_num\_seqs}=256. "
      r"The cross-language disparity reproduces on every model "
      f"(${lo:.1f}$--${hi:.1f}\\times$ between the cheapest and most expensive "
      f"language: {per_model}), and the high- "
      r"and low-resource groups never overlap on any model. "
      f"$^\\dagger$Right-censored (hit the 6-hour cap: {cen_txt}); the "
      r"steady-state window still formed, so per-token energy is valid.}")
    p(r"\label{tab: cross-model-energy-belebele}")
    p(r"\end{table}")
    OUT.write_text("\n".join(out) + "\n")
    print(f"Wrote {OUT}")
    for disp, _ in MODELS:
        print(f"  {disp:14s} disparity={disp_ratio[disp]:.1f}x")
    print("  censored:", cens)


if __name__ == "__main__":
    main()
